#!/bin/sh

# =============================================================================
# Fun Fact: we can use the following shebang line for cross-compiling:
# /* #!/bin/sh; C:/Program\ Files/path/to/Git/usr/bin/sh.exe */
# according to https://www.youtube.com/watch?v=fMYv6-SZsSo
# =============================================================================

source $(pwd)/tools/scripts/utils/logger.sh

log_info "Running post-checkout hook..."
